name: Ruff Code Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Ruff Linting (Check Code Quality)
        uses: chartboost/ruff-action@v1
        with:
          args: 'check .'

      - name: Run Ruff Formatting Check
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'